# Generated by Django 3.1.10 on 2022-03-10 13:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified At')),
                ('shape_type', models.CharField(choices=[('triangle', 'Triangle'), ('rectangle', 'Rectangle'), ('square', 'Square'), ('diamond', 'Diamond')], max_length=31)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='shape_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shape_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Shape',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.shape')),
                ('diagonal_1', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Diagonal 1')),
                ('diagonal_2', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Diagonal 2')),
            ],
            options={
                'verbose_name': 'Diamond',
                'managed': True,
            },
            bases=('backend.shape',),
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.shape')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Width')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Height')),
            ],
            options={
                'verbose_name': 'Rectangle',
                'managed': True,
            },
            bases=('backend.shape',),
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.shape')),
                ('side', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Side')),
            ],
            options={
                'verbose_name': 'Square',
                'managed': True,
            },
            bases=('backend.shape',),
        ),
        migrations.CreateModel(
            name='Triangle',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.shape')),
                ('side_a', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Side A')),
                ('side_b', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Side B')),
                ('side_c', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Side C')),
            ],
            options={
                'verbose_name': 'Triangle',
                'managed': True,
            },
            bases=('backend.shape',),
        ),
    ]
